name: exolife
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - polars
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - nodejs
  - xgboost
  - lightgbm
  - pip
  - pip:
      - astropy
      - astroquery
      - shap
      - tqdm
      - pre-commit
      - joblib
      - requests
      - pyyaml
      - black
      - isort
      - flake8
      - pytest
