name: exolife
channels:
  - conda-forge
dependencies:
  - python=3.11
  - black
  - isort
  - flake8
  - pytest
  - numpy
  - pandas
  - polars
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - ipykernel
  - nodejs
  - xgboost
  - lightgbm
  - pre-commit
  - pyarrow
  - pydantic
  - pip
  - pip:
      - astropy
      - astroquery
      - shap
      - tqdm
      - joblib
      - requests
      - pyyaml
      - click
