id: "gaia_dr2_astrophysical_parameters"
name: "Gaia DR2 Astrophysical Parameters (Fallback)"
description: "Gaia DR2 data as fallback source for stars not available in DR3. Provides basic astrometry and photometry for maximum coverage."
# Placeholder ADQL to trigger TAPFetcher selection - actual query is generated dynamically
adql: "-- Dynamic query based on NASA exoplanet host star Gaia IDs for DR2 fallback"

primary_keys:
  - "gaia_dr2_source_id"

join_keys:
  nasa_exoplanet_archive_pscomppars:
    - "gaia_id" # Maps to gaia_dr2_source_id (NASA uses DR2)
  gaia_dr2_hosts:
    - "source_id" # Maps to gaia_dr2_source_id

columns_to_keep:
  # Source identifiers (DR2 only)
  - "gaia_dr2_source_id"
  - "gaia_dr3_source_id" # Will be NULL for DR2-only data

  # Astrometry (J2015.5 epoch for DR2)
  - "ra"
  - "dec"
  - "parallax"
  - "parallax_error"
  - "pmra"
  - "pmra_error"
  - "pmdec"
  - "pmdec_error"
  - "ruwe" # Will be NULL for DR2

  # Photometry
  - "phot_g_mean_mag"
  - "phot_bp_mean_mag"
  - "phot_rp_mean_mag"
  - "bp_rp"

  # Radial velocity
  - "radial_velocity"
  - "radial_velocity_error"

  # Astrophysical parameters (not available in DR2)
  - "teff_gspphot"
  - "teff_gspphot_lower"
  - "teff_gspphot_upper"
  - "radius_gspphot"
  - "radius_gspphot_lower"
  - "radius_gspphot_upper"
  - "lum_flame"
  - "lum_flame_lower"
  - "lum_flame_upper"
  - "logg_gspphot"
  - "mh_gspphot"
  - "ag_gspphot"
  - "ebpminrp_gspphot"

# Quality filters for DR2 data
quality_filters:
  # Basic quality requirements
  parallax_positive: true
  photometry_required: true

  # Relaxed constraints for DR2 (no RUWE available)
  parallax_snr_min: 3.0 # Lower threshold for DR2

# Data source configuration
tap_endpoint: "https://gea.esac.esa.int/tap-server/tap/sync"
data_release: "DR2"
canonical_epoch: "J2015.5"
