id: "koi_candidates"
name: "Kepler Objects of Interest (KOI) - Candidate Table"
description: "Kepler Objects of Interest from NASA Exoplanet Archive with candidate status and vetting flags for stellar enrichment via host identifiers."
download_url: "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+cumulative&format=csv"

primary_keys:
  - "kepoi_name"

join_keys:
  nasa_exoplanet_archive_pscomppars:
    - "kepid"
  gaia_dr3_astrophysical_parameters:
    - "ra"
    - "dec"
  sweet_cat:
    - "ra"
    - "dec"

columns_to_keep:
  - "kepoi_name"
  - "kepler_name"
  - "kepid"
  - "ra"
  - "dec"
  - "koi_disposition"
  - "koi_pdisposition"
  - "koi_score"
  - "koi_fpflag_nt"
  - "koi_fpflag_ss"
  - "koi_fpflag_co"
  - "koi_fpflag_ec"
  - "koi_period"
  - "koi_period_err1"
  - "koi_period_err2"
  - "koi_time0bk"
  - "koi_time0bk_err1"
  - "koi_time0bk_err2"
  - "koi_eccen"
  - "koi_eccen_err1"
  - "koi_eccen_err2"
  - "koi_longp"
  - "koi_longp_err1"
  - "koi_longp_err2"
  - "koi_impact"
  - "koi_impact_err1"
  - "koi_impact_err2"
  - "koi_duration"
  - "koi_duration_err1"
  - "koi_duration_err2"
  - "koi_depth"
  - "koi_depth_err1"
  - "koi_depth_err2"
  - "koi_prad"
  - "koi_prad_err1"
  - "koi_prad_err2"
  - "koi_sma"
  - "koi_sma_err1"
  - "koi_sma_err2"
  - "koi_incl"
  - "koi_incl_err1"
  - "koi_incl_err2"
  - "koi_teq"
  - "koi_teq_err1"
  - "koi_teq_err2"
  - "koi_insol"
  - "koi_insol_err1"
  - "koi_insol_err2"
  - "koi_dor"
  - "koi_dor_err1"
  - "koi_dor_err2"
  - "koi_steff"
  - "koi_steff_err1"
  - "koi_steff_err2"
  - "koi_slogg"
  - "koi_slogg_err1"
  - "koi_slogg_err2"
  - "koi_smet"
  - "koi_smet_err1"
  - "koi_smet_err2"
  - "koi_srad"
  - "koi_srad_err1"
  - "koi_srad_err2"
  - "koi_smass"
  - "koi_smass_err1"
  - "koi_smass_err2"
  - "koi_kepmag"
  - "koi_gmag"
  - "koi_rmag"
  - "koi_imag"
  - "koi_zmag"
  - "koi_jmag"
  - "koi_hmag"
  - "koi_kmag"
  - "koi_quarters"
  - "koi_num_transits"
  - "koi_max_sngle_ev"
  - "koi_max_mult_ev"
  - "koi_model_snr"
  - "koi_model_dof"
  - "koi_model_chisq"
  - "koi_tce_plnt_num"
  - "koi_tce_delivname"
  - "koi_comment"
  - "koi_vet_stat"
  - "koi_vet_date"
  - "koi_disp_prov"
  - "koi_parm_prov"
