id: "nasa_exoplanet_archive_pscomppars"
name: "NASA Exoplanet Archive – Composite Planet Parameters (pscomppars)"
description: "Canonical, curated planet & host‑star parameters for confirmed exoplanets."
download_url: "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+pscomppars&format=csv"

primary_keys:
  - "pl_name"

join_keys:
  phl_exoplanet_catalog:
    - "P_NAME"
  sweet_cat:
    - "hostname"
    - "Name"

columns_to_keep:
  - "pl_name"
  - "pl_letter"
  - "hostname"
  - "gaia_id"
  - "sy_pnum"
  - "sy_snum"
  - "disc_year"
  - "disc_method"
  - "ra"
  - "dec"
  - "sy_dist"
  - "pl_orbper"
  - "pl_orbpererr1"
  - "pl_orbpererr2"
  - "pl_orbsmax"
  - "pl_orbsmaxerr1"
  - "pl_orbsmaxerr2"
  - "pl_orbeccen"
  - "pl_orbeccenerr1"
  - "pl_orbeccenerr2"
  - "pl_orbincl"
  - "pl_orbinclerr1"
  - "pl_orbinclerr2"
  - "pl_rade"
  - "pl_radeerr1"
  - "pl_radeerr2"
  - "pl_radj"
  - "pl_radjerr1"
  - "pl_radjerr2"
  - "pl_masse"
  - "pl_masseerr1"
  - "pl_masseerr2"
  - "pl_massj"
  - "pl_massjerr1"
  - "pl_massjerr2"
  - "pl_dens"
  - "pl_denserr1"
  - "pl_denserr2"
  - "pl_eqt"
  - "pl_eqterr1"
  - "pl_eqterr2"
  - "pl_insol"
  - "pl_insolerr1"
  - "pl_insolerr2"
  - "tran_flag"
  - "rv_flag"
  - "ttv_flag"
  - "ast_flag"
  - "ima_flag"
  - "st_teff"
  - "st_tefferr1"
  - "st_tefferr2"
  - "st_met"
  - "st_meterr1"
  - "st_meterr2"
  - "st_logg"
  - "st_loggerr1"
  - "st_loggerr2"
  - "st_lum"
  - "st_lumerr1"
  - "st_lumerr2"
  - "st_age"
  - "st_ageerr1"
  - "st_ageerr2"
  - "st_mass"
  - "st_masserr1"
  - "st_masserr2"
  - "st_rad"
  - "st_raderr1"
  - "st_raderr2"
  - "st_dens"
  - "st_denserr1"
  - "st_denserr2"
  - "sy_gmag"
  - "sy_kmag"
  - "sy_tmag"
  - "systemid"
  - "pl_pubdate"
