id: "toi_candidates"
name: "TESS Objects of Interest (TOI) - Candidate Table"
description: "TESS Objects of Interest from ExoFOP/NASA Exoplanet Archive with candidate status and vetting flags for stellar enrichment via host identifiers."
download_url: "https://exoplanetarchive.ipac.caltech.edu/TAP/sync?query=select+*+from+toi&format=csv"

primary_keys:
  - "tid"

join_keys:
  nasa_exoplanet_archive_pscomppars:
    - "tid"
  gaia_dr3_astrophysical_parameters:
    - "ra"
    - "dec"
  sweet_cat:
    - "ra"
    - "dec"

columns_to_keep:
  - "tid"
  - "toi"
  - "toidisplay"
  - "tfopwg_disp"
  - "ra"
  - "dec"
  - "pl_orbper"
  - "pl_orbpererr1"
  - "pl_orbpererr2"
  - "pl_rade"
  - "pl_radeerr1"
  - "pl_radeerr2"
  - "pl_insol"
  - "pl_insolerr1"
  - "pl_insolerr2"
  - "pl_eqt"
  - "pl_eqterr1"
  - "pl_eqterr2"
  - "st_teff"
  - "st_tefferr1"
  - "st_tefferr2"
  - "st_logg"
  - "st_loggerr1"
  - "st_loggerr2"
  - "st_rad"
  - "st_raderr1"
  - "st_raderr2"
  - "st_tmag"
  - "st_dist"
  - "st_disterr1"
  - "st_disterr2"
  - "sectors"
  - "toi_created"
  - "rowupdate"
  - "release_date"
