name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: exolife
          environment-file: environment.yml
          auto-activate-base: false

      - name: Show conda info
        run: conda info

      - name: Install dev tools
        shell: bash -l {0}
        run: |
          conda activate exolife
          pip install -U pip
          pip install black ruff

      - name: Run linters
        shell: bash -l {0}
        run: |
          conda activate exolife
          black --check --diff package
          ruff check package
